### ISSUE TITLE
cql_config program (cassandra-cpp-driver 2.7.0)

### ISSUE THREAD

**Issue by sothy** [tcely/docker-isc-kea#2]
Hello,
When I am builing docker image, I'm getting an error:
configure: error: --with-cql should point to a cql_config program

In the installion, it installs: Installing cassandra-cpp-driver-dev (2.7.0-r1)
Based on reading, dhcp server requires :v 2.8.0.
Do you know how to solve the problem?

Thanks
sothy

**Comment by tcely** [comment]
Copy https://github.com/tcely/docker-isc-kea/blob/09973a367d360d55fe6130862fd1f70243d335e1/cql_config so that it is next to `Dockerfile` and the build should be happy. 

Also, be sure that file has read & execute permission set.
